# Generated by Django 2.2.7 on 2019-11-20 15:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, verbose_name='Номер по порядку')),
                ('bigText', models.CharField(max_length=70, null=True, verbose_name='Заголовок на баннере (70 символов)')),
                ('smallText', models.CharField(max_length=200, null=True, verbose_name='Описание на баннере (200 символов)')),
                ('image', models.ImageField(blank=True, upload_to='banners/', verbose_name='Картинка для баннера (1920 x 660)')),
                ('buttonText', models.CharField(max_length=10, verbose_name='Надпись на первой кнопке')),
                ('buttonUrl', models.CharField(max_length=100, verbose_name='Ссылка с кнопки')),
                ('isActive', models.BooleanField(default=True, verbose_name='Отображать ?')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='Название проекта (30 символов)')),
                ('image', models.ImageField(blank=True, upload_to='service_img/', verbose_name='Изображение (360 x 240)')),
                ('customer', models.CharField(max_length=40, null=True, verbose_name='Заказчик')),
                ('town', models.CharField(max_length=40, null=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, verbose_name='Название услуги')),
                ('short_description', models.TextField(verbose_name='Краткое описание (380 символов)')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Полное описание услуги')),
                ('isHomeVisible', models.BooleanField(db_index=True, default=True, verbose_name='Отображать на главной?')),
                ('nameSlug', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='service_img/', verbose_name='Изображение превью для главной (360 x 240)')),
                ('pageH1', models.CharField(max_length=255, null=True, verbose_name='Тег H1')),
                ('pageTitle', models.CharField(max_length=255, null=True, verbose_name='Название страницы SEO')),
                ('pageDescription', models.CharField(max_length=255, null=True, verbose_name='Описание страницы SEO')),
                ('pageKeywords', models.TextField(null=True, verbose_name='Keywords SEO')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотров')),
                ('isActive', models.BooleanField(default=True, verbose_name='Активная услуга?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
