# Generated by Django 2.2.7 on 2019-11-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Нет данных', max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, default='Нет данных', max_length=255, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, default='Нет данных', max_length=255, verbose_name='Почта')),
                ('service', models.CharField(blank=True, default='Нет данных', max_length=255, verbose_name='Услуга')),
                ('message', models.TextField(blank=True, default='Нет данных', verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заполнения')),
            ],
            options={
                'verbose_name': 'Форма заказа звонка',
                'verbose_name_plural': 'Формы заказа звонка',
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='service_img/', verbose_name='Изображение превью для главной (360 x 240)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='pageDescription',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание страницы SEO'),
        ),
        migrations.AlterField(
            model_name='service',
            name='pageH1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1'),
        ),
        migrations.AlterField(
            model_name='service',
            name='pageKeywords',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords SEO'),
        ),
        migrations.AlterField(
            model_name='service',
            name='pageTitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO'),
        ),
    ]
