# Generated by Django 2.2.7 on 2019-11-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20191130_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='seotag',
            name='aboutDescription',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Description для страницы о компании'),
        ),
        migrations.AddField(
            model_name='seotag',
            name='aboutKeywords',
            field=models.TextField(blank=True, null=True, verbose_name='Тег Keywords для страницы о компании'),
        ),
        migrations.AddField(
            model_name='seotag',
            name='aboutTitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Title для страницы о компании'),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='contactDescription',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Description для страницы контакты'),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='contactKeywords',
            field=models.TextField(blank=True, null=True, verbose_name='Тег Keywords для страницы контакты'),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='contactTitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Title для страницы контакты'),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='projectsDescription',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Description для страницы со всеми проектами'),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='projectsKeywords',
            field=models.TextField(blank=True, null=True, verbose_name='Тег Keywords для страницы со всеми проектами'),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='projectsTitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Title для страницы со всеми проектами'),
        ),
    ]
