# Generated by Django 2.2.7 on 2019-12-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20191130_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button1Text',
            field=models.CharField(max_length=10, null=True, verbose_name='Надпись на второй кнопке'),
        ),
        migrations.AddField(
            model_name='banner',
            name='button1Url',
            field=models.CharField(max_length=100, null=True, verbose_name='Ссылка с второй кнопки'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='buttonText',
            field=models.CharField(max_length=10, null=True, verbose_name='Надпись на первой кнопке'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='buttonUrl',
            field=models.CharField(max_length=100, null=True, verbose_name='Ссылка с кнопки'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Картинка для баннера (1920 x 660)'),
        ),
    ]
