# Generated by Django 2.2.7 on 2019-12-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20191202_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Заказчик '),
        ),
    ]
