# Generated by Django 2.2.7 on 2019-12-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_service_pagespecialtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Прикрепленный файл'),
        ),
    ]
