# Generated by Django 2.2.7 on 2019-12-25 15:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_callback_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seotag',
            options={'verbose_name': 'Теги и текста для статических страниц', 'verbose_name_plural': 'Теги и текста для статических страниц'},
        ),
        migrations.AddField(
            model_name='seotag',
            name='indexText',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст на главную'),
        ),
    ]
