# Generated by Django 2.2.7 on 2020-02-12 09:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20191225_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Полное описание проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='nameSlug',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pageDescription',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание страницы SEO'),
        ),
        migrations.AddField(
            model_name='project',
            name='pageH1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1'),
        ),
        migrations.AddField(
            model_name='project',
            name='pageKeywords',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords SEO'),
        ),
        migrations.AddField(
            model_name='project',
            name='pageTitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO'),
        ),
        migrations.AlterField(
            model_name='service',
            name='nameSlug',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
