# Generated by Django 2.2.7 on 2020-03-19 17:47

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20200220_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название статьи')),
                ('short_description', models.TextField(verbose_name='Краткое описание (380 символов)')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Статья')),
                ('nameSlug', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='post_img/', verbose_name='Изображение превью (360 x 240)')),
                ('pageH1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1')),
                ('pageTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO')),
                ('pageDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание страницы SEO')),
                ('pageKeywords', models.TextField(blank=True, null=True, verbose_name='Keywords SEO')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотров')),
                ('isActive', models.BooleanField(default=True, verbose_name='Отображается?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статья',
            },
        ),
    ]
