# Generated by Django 2.2.7 on 2020-03-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_blogpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='short_description',
            field=models.CharField(max_length=255, verbose_name='Краткое описание (380 символов)'),
        ),
    ]
