# Generated by Django 2.2.7 on 2020-03-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20200319_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='seotag',
            name='blogDescription',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Description для страницы блог'),
        ),
        migrations.AddField(
            model_name='seotag',
            name='blogKeywords',
            field=models.TextField(blank=True, null=True, verbose_name='Тег Keywords для страницы блог'),
        ),
        migrations.AddField(
            model_name='seotag',
            name='blogTitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Title для страницы блог'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='short_description',
            field=models.CharField(max_length=255, verbose_name='Краткое описание (255 символов)'),
        ),
    ]
