# Generated by Django 2.2.7 on 2020-03-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image_small',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
